"""Ford Motor Company (F) five-year pro forma and FCFE valuation.

Educational FIN 43900 model. Amounts are USD millions except per-share data.
The model starts from Ford's FY2025 consolidated balance sheet and explicitly
models Ford Credit assets and debt instead of using ABG's dealer floor plan.
"""

from __future__ import annotations

import argparse


YEARS = range(2026, 2031)

# Forecast assumptions. See lab10_ford.md for labels, evidence, and reasons.
REVENUE_GROWTH = {2026: 0.020, 2027: 0.025, 2028: 0.025, 2029: 0.025, 2030: 0.020}
GROSS_MARGIN = {2026: 0.145, 2027: 0.146, 2028: 0.147, 2029: 0.148, 2030: 0.148}
SGA_TO_GROSS_PROFIT = 0.400
FORD_CREDIT_EXPENSE_TO_REVENUE = 0.059
DEPRECIATION_TO_OPENING_PPE = 0.190
CAPITAL_SPENDING = {2026: 10_000.0, 2027: 9_800.0, 2028: 10_000.0, 2029: 10_200.0, 2030: 10_400.0}
TAX_RATE = 0.210
INVENTORY_DAYS = 34.0
TRADE_RECEIVABLES_TO_REVENUE = 15_398.0 / 187_267.0
OTHER_ASSETS_TO_REVENUE = 43_583.0 / 187_267.0
PAYABLE_DAYS = 54.0
OTHER_LIABILITIES_TO_REVENUE = 64_035.0 / 187_267.0
FINANCE_ASSET_GROWTH = 0.020
FORD_CREDIT_DEBT_TO_FINANCE_ASSETS = 141_417.0 / 139_119.0
COMPANY_DEBT_REPAYMENT = {2026: 2_200.0, 2027: 500.0, 2028: 500.0, 2029: 500.0, 2030: 500.0}
COMPANY_DEBT_RATE = 0.057
OTHER_INCOME_TO_REVENUE = 0.010
DIVIDENDS = 2_400.0
MARKETABLE_SECURITIES = 15_131.0
COMPANY_CASH_FLOOR = 20_000.0
REVOLVER_LIMIT = 18_000.0
COST_OF_EQUITY = 0.100
TERMINAL_GROWTH = 0.020
SHARES_OUTSTANDING = 3_979.0

# FY2025 opening consolidated balance sheet from Ford's 2025 Form 10-K.
OPENING = {
    "revenue": 187_267.0,
    "cash": 23_356.0,
    "marketable_securities": 15_131.0,
    "finance_assets": 139_119.0,  # Ford Credit receivables + operating leases
    "trade_receivables": 15_398.0,
    "inventory": 15_285.0,
    "ppe": 37_288.0,
    "other_assets": 43_583.0,
    "payables": 25_809.0,
    "other_liabilities": 64_035.0,
    "company_debt": 21_919.0,
    "ford_credit_debt": 141_417.0,
    "revolver": 0.0,
    "equity": 35_980.0,
}


def build_projection() -> list[dict[str, float]]:
    """Build linked income statement, balance sheet, and cash-flow rows."""
    forecasts = []
    opening = OPENING.copy()

    for year in YEARS:
        revenue = opening["revenue"] * (1.0 + REVENUE_GROWTH[year])
        gross_profit = revenue * GROSS_MARGIN[year]
        cost_of_sales = revenue - gross_profit
        sga = gross_profit * SGA_TO_GROSS_PROFIT
        ford_credit_expense = revenue * FORD_CREDIT_EXPENSE_TO_REVENUE
        operating_income = gross_profit - sga - ford_credit_expense
        interest_expense = opening["company_debt"] * COMPANY_DEBT_RATE
        other_income = revenue * OTHER_INCOME_TO_REVENUE
        pretax_income = operating_income - interest_expense + other_income
        tax = max(0.0, pretax_income) * TAX_RATE
        net_income = pretax_income - tax

        depreciation = opening["ppe"] * DEPRECIATION_TO_OPENING_PPE
        capital_spending = CAPITAL_SPENDING[year]
        marketable_securities = MARKETABLE_SECURITIES
        finance_assets = opening["finance_assets"] * (1.0 + FINANCE_ASSET_GROWTH)
        trade_receivables = revenue * TRADE_RECEIVABLES_TO_REVENUE
        inventory = cost_of_sales * INVENTORY_DAYS / 365.0
        ppe = opening["ppe"] + capital_spending - depreciation
        other_assets = revenue * OTHER_ASSETS_TO_REVENUE

        payables = cost_of_sales * PAYABLE_DAYS / 365.0
        other_liabilities = revenue * OTHER_LIABILITIES_TO_REVENUE
        company_debt = max(0.0, opening["company_debt"] - COMPANY_DEBT_REPAYMENT[year])
        ford_credit_debt = finance_assets * FORD_CREDIT_DEBT_TO_FINANCE_ASSETS
        equity = opening["equity"] + net_income - DIVIDENDS

        changes = {
            "marketable_securities": marketable_securities - opening["marketable_securities"],
            "finance_assets": finance_assets - opening["finance_assets"],
            "trade_receivables": trade_receivables - opening["trade_receivables"],
            "inventory": inventory - opening["inventory"],
            "other_assets": other_assets - opening["other_assets"],
            "payables": payables - opening["payables"],
            "other_liabilities": other_liabilities - opening["other_liabilities"],
            "company_debt": company_debt - opening["company_debt"],
            "ford_credit_debt": ford_credit_debt - opening["ford_credit_debt"],
        }

        # Cash is generated by the linked statements, not typed as a plug.
        fcfe = (
            net_income
            + depreciation
            - capital_spending
            - changes["finance_assets"]
            - changes["trade_receivables"]
            - changes["inventory"]
            - changes["other_assets"]
            + changes["payables"]
            + changes["other_liabilities"]
            + changes["company_debt"]
            + changes["ford_credit_debt"]
        )
        cash_before_revolver = (
            opening["cash"]
            + fcfe
            - DIVIDENDS
            - changes["marketable_securities"]
        )

        minimum_cash = max(0.0, COMPANY_CASH_FLOOR - marketable_securities)
        revolver = opening["revolver"]
        revolver_draw = 0.0
        if cash_before_revolver < minimum_cash:
            revolver_draw = minimum_cash - cash_before_revolver
            if revolver + revolver_draw > REVOLVER_LIMIT:
                raise ValueError(f"FY{year}E exceeds the revolver limit")
            revolver += revolver_draw
            cash = minimum_cash
        else:
            revolver_repayment = min(
                opening["revolver"], cash_before_revolver - minimum_cash
            )
            revolver -= revolver_repayment
            cash = cash_before_revolver - revolver_repayment

        total_assets = (
            cash
            + marketable_securities
            + finance_assets
            + trade_receivables
            + inventory
            + ppe
            + other_assets
        )
        total_liabilities_and_equity = (
            payables
            + other_liabilities
            + company_debt
            + ford_credit_debt
            + revolver
            + equity
        )

        row = {
            "year": float(year),
            "revenue": revenue,
            "gross_profit": gross_profit,
            "cost_of_sales": cost_of_sales,
            "sga": sga,
            "ford_credit_expense": ford_credit_expense,
            "operating_income": operating_income,
            "interest_expense": interest_expense,
            "other_income": other_income,
            "pretax_income": pretax_income,
            "tax": tax,
            "net_income": net_income,
            "depreciation": depreciation,
            "capital_spending": capital_spending,
            "cash": cash,
            "marketable_securities": marketable_securities,
            "finance_assets": finance_assets,
            "trade_receivables": trade_receivables,
            "inventory": inventory,
            "ppe": ppe,
            "other_assets": other_assets,
            "total_assets": total_assets,
            "payables": payables,
            "other_liabilities": other_liabilities,
            "company_debt": company_debt,
            "ford_credit_debt": ford_credit_debt,
            "revolver": revolver,
            "equity": equity,
            "total_liabilities_and_equity": total_liabilities_and_equity,
            "dividends": DIVIDENDS,
            "revolver_draw": revolver_draw,
            "fcfe": fcfe,
            "balance_gap": total_assets - total_liabilities_and_equity,
        }
        forecasts.append(row)
        opening = row

    return forecasts


def assert_balanced(forecasts: list[dict[str, float]]) -> None:
    """Refuse a broken balance sheet or a liquidity pool below Ford's floor."""
    for row in forecasts:
        assets = sum(
            row[key]
            for key in (
                "cash",
                "marketable_securities",
                "finance_assets",
                "trade_receivables",
                "inventory",
                "ppe",
                "other_assets",
            )
        )
        liabilities_and_equity = sum(
            row[key]
            for key in (
                "payables",
                "other_liabilities",
                "company_debt",
                "ford_credit_debt",
                "revolver",
                "equity",
            )
        )
        gap = assets - liabilities_and_equity
        if abs(gap) >= 0.05:
            raise ValueError(f"FY{int(row['year'])}E balance-sheet gap: {gap:.1f}")
        liquidity_pool = row["cash"] + row["marketable_securities"]
        if liquidity_pool + 0.05 < COMPANY_CASH_FLOOR:
            raise ValueError(
                f"FY{int(row['year'])}E cash pool {liquidity_pool:.1f} is below "
                f"the {COMPANY_CASH_FLOOR:.1f} floor"
            )


def print_table(title: str, lines: list[tuple[str, str]], forecasts: list[dict[str, float]]) -> None:
    width = max(len(label) for label, _ in lines)
    print(f"\n{title}")
    print(f"{'USD millions':<{width}}" + "".join(f"FY{y}E".rjust(13) for y in YEARS))
    print("-" * (width + 13 * len(forecasts)))
    for label, key in lines:
        values = "".join(f"{row[key]:13,.1f}" for row in forecasts)
        print(f"{label:<{width}}{values}")


def print_statements(forecasts: list[dict[str, float]]) -> None:
    print_table(
        "INCOME STATEMENT",
        [
            ("Revenue", "revenue"),
            ("Cost of sales", "cost_of_sales"),
            ("Gross profit", "gross_profit"),
            ("SG&A", "sga"),
            ("Ford Credit expense", "ford_credit_expense"),
            ("Operating income", "operating_income"),
            ("Company interest expense", "interest_expense"),
            ("Other income", "other_income"),
            ("Pretax income", "pretax_income"),
            ("Tax", "tax"),
            ("Net income", "net_income"),
        ],
        forecasts,
    )
    print_table(
        "BALANCE SHEET",
        [
            ("Cash", "cash"),
            ("Marketable securities", "marketable_securities"),
            ("Ford Credit finance assets", "finance_assets"),
            ("Trade receivables", "trade_receivables"),
            ("Inventory", "inventory"),
            ("Net PP&E", "ppe"),
            ("Other assets", "other_assets"),
            ("Total assets", "total_assets"),
            ("Payables", "payables"),
            ("Other liabilities", "other_liabilities"),
            ("Company debt", "company_debt"),
            ("Ford Credit debt", "ford_credit_debt"),
            ("Revolver", "revolver"),
            ("Equity", "equity"),
            ("Total liabilities & equity", "total_liabilities_and_equity"),
        ],
        forecasts,
    )
    print_table(
        "CASH FLOW / FCFE",
        [
            ("Net income", "net_income"),
            ("Depreciation", "depreciation"),
            ("Capital spending", "capital_spending"),
            ("FCFE", "fcfe"),
            ("Dividends", "dividends"),
            ("Revolver draw", "revolver_draw"),
        ],
        forecasts,
    )


def print_checks(forecasts: list[dict[str, float]]) -> None:
    print("\nCHECKS")
    print(f"{'':32}" + "".join(f"FY{y}E".rjust(13) for y in YEARS))
    gaps = ""
    for row in forecasts:
        assets = sum(
            row[key]
            for key in (
                "cash",
                "marketable_securities",
                "finance_assets",
                "trade_receivables",
                "inventory",
                "ppe",
                "other_assets",
            )
        )
        liabilities_and_equity = sum(
            row[key]
            for key in (
                "payables",
                "other_liabilities",
                "company_debt",
                "ford_credit_debt",
                "revolver",
                "equity",
            )
        )
        gaps += f"{assets - liabilities_and_equity:13.1f}"
    floor_checks = "".join(
        f"{('PASS' if row['cash'] + row['marketable_securities'] >= COMPANY_CASH_FLOOR else 'FAIL'):>13}"
        for row in forecasts
    )
    print(f"{'Assets - liabilities - equity':32}{gaps}")
    print(f"{'Cash pool at/above floor':32}{floor_checks}")


def value_equity(forecasts: list[dict[str, float]]) -> float:
    positive_pv = 0.0
    for index, row in enumerate(forecasts, start=1):
        if row["fcfe"] > 0:
            positive_pv += row["fcfe"] / (1.0 + COST_OF_EQUITY) ** index
        else:
            print(f"FY{int(row['year'])}E: negative FCFE; excluded from value")

    terminal_value = 0.0
    if forecasts[-1]["fcfe"] > 0:
        terminal_value = (
            forecasts[-1]["fcfe"]
            * (1.0 + TERMINAL_GROWTH)
            / (COST_OF_EQUITY - TERMINAL_GROWTH)
        )
    else:
        print("No terminal value: capitalizing a negative cash flow does not produce an economic value.")

    equity_value = positive_pv + terminal_value / (1.0 + COST_OF_EQUITY) ** 5
    value_per_share = equity_value / SHARES_OUTSTANDING
    print("\nVALUATION")
    print(f"Present value of positive explicit FCFE: ${positive_pv:,.1f} million")
    print(f"Present value of terminal value: ${terminal_value / (1.0 + COST_OF_EQUITY) ** 5:,.1f} million")
    print(f"Equity value: ${equity_value:,.1f} million")
    print(f"Shares: {SHARES_OUTSTANDING:,.1f} million")
    print(f"Value per share: ${value_per_share:,.2f}")
    return value_per_share


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--break-check",
        action="store_true",
        help="deliberately break FY2028 cash to demonstrate refusal",
    )
    args = parser.parse_args()

    forecasts = build_projection()
    if args.break_check:
        forecasts[2]["cash"] += 100.0

    print_statements(forecasts)
    print_checks(forecasts)
    assert_balanced(forecasts)
    value_equity(forecasts)


if __name__ == "__main__":
    main()
